a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('style.tcss', '.'),],

    hiddenimports=[
        'textual',
        'textual.app',
        'textual.widgets',
        'textual.widgets._text_area',
        'textual.screen',
        'textual.containers',
        'textual.message',
        'textual.css',
        'textual.css.query',
        'textual.css.scalar',
        'textual._text_area_theme',
        'textual.reactive',
        'rich',
        'rich.markdown',

        'cffi',
        'curl_cffi',
        'curl_cffi.requests',

        'dotenv',
        
        'email',
        'httpx',
        'httpcore',
        'anyio',
        'anyio._backends._asyncio',
        'asyncio',
    ],

    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'sqlite3',
        'unittest',
        'pydoc',
        'xmlrpc',
        'doctest',
        'ftplib',
        'imaplib',
        'poplib',
        'smtplib',
        'telnetlib',
        'nntplib',
    ],

    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Obsidian TUI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    optimize=2,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="favicon.ico",
)
